Repository KIT-CMS/Excalibur, pull requests merged in 2020-08, with the labels that each got.

#59 Added filter for filtering events using METFilters
  Compile/interface/Filters/ZJetCutsFilter.h
  Compile/interface/ZJetSettings.h
  Compile/src/ZJetFactory.cc
  cfg/python/defaultconfig.py
Labels: enhancement

#60 Fixed bug in ZJetProduct::GetTransverseAngleCosine
  Compile/interface/ZJetProduct.h
Labels: bug, prio:major

#61 [ZJetGenWeightProducer] Implemented default behaviour for weight filling
  Compile/interface/Producers/ZJetGenWeightProducer.h
  Compile/src/Producers/ZJetGenWeightProducer.cc
Labels: enhancement, prio:major

#67 Prevent JER smearing in data and check for negative smearing factors.
  Compile/src/Producers/JERSmearer.cc
Labels: bug, prio:minor, question
